// import type { Metadata } from "next";
import { cn } from "../lib/utils"
import { Inter as FontSans } from "next/font/google"
import type { ReactNode } from "react";
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html className="dark" lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased ",
          fontSans.variable
        )}
      >
        <div className={"relative flex min-h-screen flex-col bg-background"}>
            <div className={"w-full h-full theme-zinc"}>
              {children}
            </div>
          </div>
        </body>
    </html>
  );
}
